# Generated by Django 6.0.2 on 2026-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('mobile', 'Mobile Shop'), ('beauty', 'Beauty Parlour'), ('flower', 'Flower Shop')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='business/')),
            ],
            options={
                'verbose_name': 'Business Image',
                'verbose_name_plural': 'Business Images',
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('mobile', 'Mobile Shop'), ('beauty', 'Beauty Parlour'), ('flower', 'Flower Shop')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
            },
        ),
    ]
