# Generated by Django 6.0.2 on 2026-09-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileHeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'verbose_name': 'Mobile Hero Banner',
                'verbose_name_plural': 'Mobile Hero Banner',
            },
        ),
    ]
