# Generated by Django 6.0.6 on 2026-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=20, verbose_name='WhatsApp Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('shop', models.CharField(choices=[('mobile', '📱 Mobile Shop'), ('parlour', '💄 Beauty Parlour'), ('flower', '🌸 Flower Shop'), ('general', '🏪 All / General')], default='general', max_length=20, verbose_name='Shop')),
                ('subject', models.CharField(choices=[('price_inquiry', 'Price Inquiry'), ('appointment', 'Book Appointment'), ('order', 'Place an Order'), ('complaint', 'Complaint / Feedback'), ('wholesale', 'Wholesale / Bulk'), ('other', 'Other')], max_length=30, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
