# Generated by Django 6.0.2 on 2026-09-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('metre', '/ metre'), ('onwards', 'onwards'), ('dozen', '/ dozen'), ('string', '/ string'), ('day', '/ day'), ('set', '/ set')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Flower Pricing',
            },
        ),
    ]
