# Generated by Django 6.0.2 on 2026-09-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('hair_cut', 'Hair Cut'), ('hair_wash', 'Hair Wash'), ('luxury_facial', 'Luxury Facial'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('hair_spa', 'Hair Spa'), ('waxing', 'Waxing'), ('henna', 'Henna')], max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Beauty Pricing',
                'verbose_name_plural': 'Beauty Pricing',
                'ordering': ['service'],
            },
        ),
    ]
